### PR TITLE
Configure and apply rustfmt

### PR DESCRIPTION
**Pull request by ryanisaacg**
Unfortunately this requires nightly rustfmt, but the stable rustfmt has terrible support for nested `use` in my opinion.

### CODE REVIEW

**Comment by Byter09** [comment]
How exactly did the CI change? Is there even a check? If not I suggest using:
`cargo fmt --all -- --write-mode=diff`
This will exit with an error code and give you the difference if something is not correctly formatted.

Also, Thats a lot of changes and I just now created a branch to test polygons 😭

**Comment by ryanisaacg** [comment]
To be honest, I'm not taking too kindly to rustfmt breaking a build with no indication to me that it was running erroneously. I don't think rustfmt is particularly ready for prime-time, maybe I'll try this again when it's at 1.0.

I guess you don't have to worry about your polygon PR @Byter09

**Comment by ryanisaacg** [comment]
In fact, I didn't even add rustfmt to my CI; running rustfmt on the code broke it and the code failed CI.

I meant you don't have to worry about merging format changes into your branch, by all means continue with the work on your PR, it sounds interesting and useful.

**Comment by Byter09** [comment]
Hah 😄 
I'm currently not set up to test wasm but building quicksilver after applying rustfmt ends in tons of changes and a successful build. Works for desktop on Windows, Kubuntu and Debian. But I now understand what you ment when you said rustfmt is wonky 😅

**Pull request closed without merging**
