### PR TITLE
Create a new more convenient draw interface

### LINKED ISSUE #276: Clean up Drawable and rendering API frontend
There are a few principle problems:

- It's difficult to add support for new shapes: the only way to do it is to find a way to construct iterators
- Drawing requires unnecessary ceremony:

```rust
window.draw(&Sprite::image(&some_image, Vector::new(15, 15)).with_transform(Transform::rotate(45)).with_color(Color::green());
```

This could be written much simpler with a few method overloads like `draw`, `draw_blend`, `draw_trans`, and `draw_ex`, looking something like:

```rust
window.draw_ex(&some_image, Vector::new(15, 15), Transform::rotate(45), Color::green());
```

This would require some large changes. Namely:

- Drawable would need to have Transform and Color be parameters, not stored in the struct itself.
- Applying a blend and transform to an entire batch of vertices should be simple.
- Sprite should be removed, or it must be reversed in usage (`sprite.draw(window)` rather than `window.draw(sprite)`)

### PR DESCRIPTION
**Pull request by ryanisaacg**
- [x] Create the basics of a new draw system
- [x] Update the changelog

Resolves #276

### CODE REVIEW

**Comment by Byter09** [comment]
So it is 2:45 in the morning and I flew over your code and oh my god you nailed that.

Also that RGB triangle example is really hello-world-ish and was kind of missing wasn't it? :D

Anyway. Awesome stuff. I love it.

If you don't want to bother with the line functionality, leave it to me. Together with triangles, I can make a PR in about two days, maybe one. Depends on my free time.
If I can figure out how to draw single pixels (probably by using `Vector`s), I can even write an AA algorithm. Though I believe it's going to be pretty CPU heavy if not implemented as a shader? Going to test it though!

**Comment by ryanisaacg** [comment]
@Byter09 MSAA should definitely be possible using OpenGL, rather than having to be on the CPU. I think that it would be best implemented in the `Surface` API, so the idea would be that you draw your data to a Surface with AA on then you draw that surface to the screen.

**Comment by Byter09** [comment]
@ryanisaacg Oh right, I totally forgot MSAA exists 🙃
It is an approvement over having no AA at all, but gets kind of heavy when dealing with todays maximum resolutions. I believe MSAA is mentioned in #254, but I'm still looking into having something lighter or completely new, that only smoothes some Drawables. Candidates would be FXAA (this would have to happen right before `window.present()` or per-Drawable-AA (which is a bit harder as it requires vertice-manipulation on every draw call).

As always, I'm having fun playing around with this engine. If something useful comes up, you'll be the first to notice 😄

**Comment by ryanisaacg** [comment]
So I'm thinking a Sprite to tie together a Drawable and a DrawAttributes might be best suited for its own PR, with a comprehensive system of a Sprite scene graph and relative transforms. This PR will just be for the new draw system.

**Comment by Byter09** [comment]
Please excuse my curiosity, but would a sprite then be nothing else as a mesh? As far as I know, a mesh allows relative transformations and contains several drawable objects... Right?

**Pull request merged**
