### PR TITLE
Renamed two types

### PR DESCRIPTION
**Pull request by Xoronic**

### CODE REVIEW

**Comment by Xoronic** [comment]
Oops, lets not merge yet. I forgot to update the readme.

**Comment by ryanisaacg** [comment]
Yeah, I really should set up a CI script that ensures the README code snippet is up to date.

**Comment by ryanisaacg** [comment]
This seems good to merge, anything you want to change before I do? @Xoronic

**Comment by Xoronic** [comment]
No it is ready for merging :)

**Pull request merged**
