### PR TITLE
Support change mouse cursor style

### PR DESCRIPTION
**Pull request by Riey**
Support change cursor style using ``Window::set_cursor`` and MouseCursor

## Motivation and Context

Though winit and stdweb alreay support change cursor style quicksilver doesn't support that now

## Screenshots (if appropriate):

running set-cursor example on archlinux@firefox-64

screenshot_20190101_160459
screenshot_20190101_160525
screenshot_20190101_160552

## Types of changes
- New feature (non-breaking change which adds functionality)

## Checks

- [x] I have read `CONTRIBUTING.md`.
- [x] This Pull Request targets the right branch 
- [x] I have updated `CHANGES.md`, with [BREAKING] next to all breaking changes
- [x] I have updated the documentation accordingly if necessary
- [x] I have updated / added tests to cover my changes if necessary

- [x] The example found in `README.md` compiles and functions like expected
- [x] The example found in `src/lib.rs` compiles and functions like expected

### CODE REVIEW

**Comment by ryanisaacg** [comment]
@Riey This looks really great! The only thing I'd ask is that you make a "None" variant of the cursor, and merge showing / hiding the cursor and setting it to "None."

The reason I say this is that currently, if I hide the cursor and then set it to "grab," on desktop it appears that will mean I have an invisible grab cursor. On web, I will have a visible grab cursor. If the no-cursor state is part of the enum, this confusion won't happen.

**Comment by Riey** [comment]
I think simplest solution is add _None_ variant into _MouseCursor_ then remove _show_cursor_ and left only _set_cursor_
but it break backwards compatible

So for support both method in WebGLBackend I use a flag variable for check cursor is visible
current code has bug for that and now I fix it

**Comment by ryanisaacg** [comment]
It's actually possible to make `None` a variant of mouse cursor and maintain backwards compatibility: have show_cursor set the cursor to default on true, and to none on false, and deprecate show_cursor.

**Comment by Riey** [comment]
Oh understand yes if deprecate show_cursor that's good idea

**Pull request merged**
