### PR TITLE
Use constants instead of functions for Vectors' "presets"

### PR DESCRIPTION
**Pull request by Xoronic**
## Description

Instead of functions for the "presets" of Vectors, constants will be used. 

**Previously**
```rust
let vec = Vector::one();
```

**Now**
```rust
let vec = Vector::ONE;
```

## Motivation and Context

Using constants is clearer to the API consumer, more efficient in some cases and it provides consistency with the rest of the API.

## Screenshots (if appropriate):
None.

## Types of changes

- [x] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)

### Always
- [x] `CHANGES.md` is updated.
- [x] I have read `CONTRIBUTING.md`.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] This Pull Request targets the right branch.
- [x] Present-tense is used in commit-summaries
- [x] I have updated tests to cover my changes.
- [ ] I have added tests to cover my changes.

### If the Pull Request affects the public API
- [x] The example found in `README.md` compiles and functions like expected
- [x] The title of the change in `CHANGES.md` starts with [BREAKING] if this is a breaking change

### CODE REVIEW

**Comment by Xoronic** [comment]
Is there any way to make travis-ci retry? I think the error is not due to an external error..

**Comment by ryanisaacg** [comment]
@Xoronic done, yeah I'm unsure why Travis occasionally fails.

**Comment by ryanisaacg** [comment]
@Xoronic is this ready to merge?

**Comment by Xoronic** [comment]
Yes.

**Pull request merged**
