### PR TITLE
API experiment

### PR DESCRIPTION
**Pull request by Xoronic**
I did some weird things as an experiment:
- Changed WindowBuilder to take a vector as size-argument
- Made tuples of two Scalars implicitly convert to a Vector (using `Into`)
- Changed the Vector's 'presets' (one(), zero(), x(),....) to match the Color's presets style (constants)

Let me know if you like any of these  :)

### CODE REVIEW

**Comment by Xoronic** [comment]
The drawback of tuple conversion is that it introduces a bit of visual clutter for a lot of functions, like seen here:
https://github.com/Xoronic/quicksilver/blob/e9ef4dd1ca1b2718a46b495b22a7dbdbf7371f9c/src/geom/objects/line.rs#L27

**Comment by Byter09** [comment]
I like what you did with the vector constants but I don't know what to think of the tuples. I'm a fan of the quick and clean
```rust
let vec = (4, 2).into();
```
But at the same time I'm not sure this won't look way too cluttered in other parts of quicksilver, as you already demonstrated.

**Comment by ryanisaacg** [comment]
I greatly appreciate this!

Getting all of the constant-functions to be actual constants is on my mental list of things to do before the next release, so thanks for taking care of them for Vector!

I also like the tuple-into, because it makes code like:

```rust
Triangle::newv(Vector::new(0, 0), Vector::new(1, 0), Vector::(0, 1))
```

much cleaner:

```rust
Triangle::newv((0, 0), (1, 0), (0, 1))
```

Personally, I'm fine with a bit of clutter in the geometry function declarations themselves for a huge ergonomics gain for the rest of the library and the end users.

I'm not sure where I stand on the WindowBuilder constructor change. On one hand, it's definitely more noise to write a tuple or Vector constructor than just writing the numbers. On the other, I tend to have a `WINDOW_SIZE` constant Vector. Possibly adding a `newv` variant for WindowBuilder is the best path?

**Comment by ryanisaacg** [comment]
Oh, one more thing: if it would be convenient, I think this should be three different PRs: one for renaming the Vector constants, one for the tuple-into, and one for WindowBuilder::new. If it's too much effort to untangle this time, that's fine, but try to keep each PR to one concrete change in the future.

**Comment by Xoronic** [comment]
Glad my ideas are well received! I will untangle the PR's, that should not be that much work. 

### My suggestion
> I'm not sure where I stand on the WindowBuilder constructor change. [..] Possibly adding a newv variant for WindowBuilder is the best path?

It may be a bit radical, but I suggest:
 - Accepting `Vector`s in all `new` functions where appropriate (for locations and sizes) and removing all the `newv` functions
 - Let the WindowBuilder constructor take a `Vector` as size argument

Because I think that the `new` functions like [this](https://github.com/Xoronic/quicksilver/blob/e9ef4dd1ca1b2718a46b495b22a7dbdbf7371f9c/src/geom/objects/triangle.rs#L18) were written because of the visual clutter of the `Vector::new` function. As that does not form a problem anymore, removing them would greatly improve the consistency in the API. 

> I'm not sure where I stand on the WindowBuilder constructor change. On one hand, *it's definitely more noise to write a tuple or Vector constructor than just writing the numbers*. On the other, I tend to have a WINDOW_SIZE constant Vector.

I think the parenthesis are clearer and less confusing. API consumers won't have to think about the arguments: if they must enter a size, it is always a `Vector` (or tuple of course).

I think that
```rust
Triangle::new((0, 0), (1, 0), (0, 1))
```
is really clean for example.

### Overhead?
> EDIT: Also, having WindowBuilder use a Vector instead of primitives is... A bit of overhead, don't you think?

I think that the overhead is negligible (even optimized away if the windowsize is a constant). If there is any problem here, I think that it is the Vector having a conversion overhead, not that the WindowBuilder uses a Vector. Maybe not all Vectors should contain floats by default, and only be converted if necessary?

**Comment by Byter09** [comment]
About that triangle constructor: point taken. It's not pretty. But I guess that happens when you have 6 parameters :P

Now, let's say all this happens and this PR is accepted as is, is there a way to provide inputs, which use different primitives but end up being `Scalar` anyway?
Right now doing the following is not possible, but it would make things so much easier:
```rust
let vec = Vector::new(0.5, 1);
```
0.5 and 1 are of different types, in which case one has to write 1.0. I know its not much but while we're at it, this should be possible, or is already possible with this PR, right? (On my phone right now, can't look at all your changes :P)

**Comment by Xoronic** [comment]
That's already possible with this PR! I ran onto exactly the same issue and I fixed it by adding another parameter, so that two different scalar types are allowed. You can find that [here](https://github.com/Xoronic/quicksilver/blob/e9ef4dd1ca1b2718a46b495b22a7dbdbf7371f9c/src/geom/vector.rs#L42). I did it for both the old `new` function and for the tuple approach.

**Comment by Xoronic** [comment]
So they're not both type T, but type T and type U

**Comment by ryanisaacg** [comment]
The best solution for something like that is generally impl Trait, so that each parameter would be `impl Scalar`.

**Comment by Byter09** [comment]
So like this then?
```rust
pub fn new(x: impl Scalar, y: impl Scalar) -> Vector {
```

Yeah right. But this would push the lower supported rustc version to... 1.26 I believe? Not that it matters. Just saying.

**Comment by ryanisaacg** [comment]
Due to some uses of the new match syntax sugar in Rust 1.27, we're well past that. Generally I wait for a week or two, but `development` tends to track the latest stable Rust quite closely.

**Comment by Xoronic** [comment]
Ah, I did not know about `impl Trait`! I will use that instead, it reads a bit nicer.

**Comment by Xoronic** [comment]
> *Changed the Vector's 'presets' (one(), zero(), x(),....) to match the Color's presets style (constants)* 

can be found in #296

I will create PR's for the other two later :P

**Comment by Xoronic** [comment]
I will close this PR as the changes are separated over different pull requests.

**Pull request closed without merging**
