### PR TITLE
Stdweb integration

### LINKED ISSUE #220: stdweb integration
stdweb and wasm-bindgen seem like they would make the JS side of the web deployment much simpler and much more integrated into the Rust ecosystem.

### PR DESCRIPTION
**Pull request by ryanisaacg**
Stdweb is definitely at the point where if you accept cargo-web as a necessary dependency, it is definitely better than maintaining a separate JS file for bindings. 

- [x] Drawing
     - [x] Acquire a WebGL context from the canvas
     - [x] Loading WebGL functions
     - [x] Split the webgl and desktop GL backends
     - [x] GL Viewports
- [x] File loading (dependent on futures integration?)
- [x] Gamepad buttons
- [x] Images
    - [x] Image loading (futures?)
    - [x] Passing images to WebGL
    - [x] Unloading images when they leave scope
    - [x] Stop unpacking and repacking errors from the image crate
- [x] Saving
    - [x] Saving
    - [x] Loading
- [x] Sounds
     - [x] Sound loading (futures?)
     - [x] Playing sounds
- [x] Windowing
     - [x] Show/hide mouse
     - [x] Get width / height
     - [x] Create context
     - [x] Set title
- [x] Events
     - [x] Close
     - [x] Focus / unfocus
     - [x] Key input
     - [x] Mouse movement
     - [x] Mouse enter / leave
     - [x] Mouse press / release
     - [x] Mouse wheel
     - [x] Gamepad connect / disconnect
- [x] Lifecycle
     - [x] Update ticks
     - [x] Render ticks
- [x] Update documentation in the README

Resolves #220

### CODE REVIEW

**Comment by ryanisaacg** [comment]
Blocked waiting for the next release of stdweb, which will land gamepad support

**Comment by ryanisaacg** [comment]
Progress: the draw-geometry example can now be built and run with the stdweb backend!

**Comment by ryanisaacg** [comment]
Not going to bother with

**Comment by kevinw** [comment]
Why did State gain the 'static lifetime/

**Comment by ryanisaacg** [comment]
I believe it's a requirement for items passed into stdweb callbacks.

**Comment by kevinw** [comment]
One other question--is there a small write-up for how to run one of the
examples on the development branch with `cargo web`?

**Comment by ryanisaacg** [comment]
Not really at the moment. Basically, you need to:

- Create a project
- Add quicksilver's development branch as a git dependency
- Replace the project's main.rs file with the contents of the example
- Create an HTML file called "index.html" in a folder called "static", with a canvas element with id "canvas"
- Point that HTML file at the script cargo-web generates

It's pretty involved currently, and I want to automate it or at least make it easier before the next release, hence the lack of a write-up.

**Pull request merged**
