### PR TITLE
Bump to version 0.3.0

### LINKED ISSUE #302: Version 0.3 release roadmap
Given the large-scale changes to the API, and the introduction of stdweb, this obviously is a huge breaking release, warranting a 0.x bump. 

In general, I want the 0.3 release to focus on improving the core features and some integration with other crates that is relatively trivial (immi, for example.) Large scale efforts like #229 that basically require re-creating the entire API in a new language are off the table.

Current blockers:

- [x] Windowing API (#16, #262, #230) : There is a showstopping bug in fullscreen windows on the web. Is the current behavior even beneficial? Should the web just ignore the fullscreen setting? Additionally, the updates to glutin and winit warrant a second look to see if adjusting Window settings after it has been built is feasible.
- [x] API robustness (#234): Error bubbling should go a long way to improving debugability, but on the web panics can be hard to diagnose or track down. Possibly, the user should be able to supply some sort of error-handling callback to avoid panics inside the update and draw callbacks.
- [x] immi support (#218): Considering the work has already begun, this should be finished before the next release
- [x] Tutorials (#221): Currently the documentation is pretty sparse, so this should help quite a bit
- [x] lyon support (#247): Adding lyon support gives the draw pipeline a huge boost in flexibility for comparatively little effort
- [x] Some form of AA (#254): MSAA, at the very least, seems achievable without a great amount of effort
- [x] Shape API overhaul (#264): There's a lot that can be done here, but at the very least there should be a common overlap trait that all shapes share
- [x] must_use (#286): This is a small tweak that will fix a minor but common issue while programming
- [x] Dyn trait (#300): A small tweak that will make the Rust 2015 -> Rust 2018 transition easier
- [x] Draw API (#276, #315): The Draw API should strike a balance between too verbose (requiring every Drawable to be wrapped in a builder type for example) and too large an API surface, as well as striving for consistency, documentation, and good naming
- [x] Version bumps (#319, #320) In addition to the more complex bumps, making sure nalgebra, alga, and ncollide can be upgraded
- [x] Variable draw rate (#314): A breaking change that shouldn't be too hard to implement
- [x] Unified asset loading (#331): Without landing this, using Quicksilver for both web and desktop will be impossible without modifications between each build
- [x] Feature build issues (#338): Quicksilver should build fine without the optional features and this should be tested on CI
- [x] WASM asset bugs (#348, #349): These are very showstopping bugs which need to be resolved before a release
- [x] Rename the `Mesh::apply` function (#371): This is a very small change but it's a good one to make before the Mesh API becomes more stable
- [x] Mac fullscreen is broken (#372): A bug discovered while doing pre-release testing
- [x] Document required packages on Linux (#375): While testing Quicksilver on a fresh install I noticed that Ubuntu doesn't ship some necessary packages by default

### PR DESCRIPTION
**Pull request by ryanisaacg**
Now that all the 0.3.0 milestones have been hit, it's time to make the release.

## Motivation and Context
Resolves #302 

## Checks

- [x] I have read `CONTRIBUTING.md`.
- [x] This Pull Request targets the right branch 
- [x] I have updated `CHANGES.md`, with [BREAKING] next to all breaking changes
- [x] I have updated the documentation accordingly if necessary
- [x] I have updated / added tests to cover my changes if necessary

### CODE REVIEW

**Comment by Xoronic** [comment]
Congratulations! :P This is such a big update!

Don't forget to add this version to cargo by the way.

And *In-development* should be replaced by *v0.3.0* in [CHANGES.md](https://github.com/ryanisaacg/quicksilver/blob/master/CHANGES.md). (That might be something you want to add to the release checklist)

**Comment by ryanisaacg** [comment]
@Xoronic Thanks for spotting that, fixed now 👍

**Comment by Xoronic** [comment]
It looks like [Docs.rs failed building quicksilver-docs](https://docs.rs/crate/quicksilver/0.3.0/builds/117161)

**Comment by ryanisaacg** [comment]
I'm probably going to look into self-hosting documentation because this is the second time we've hit an issue with docs.rs's version of the compiler.

**Pull request merged**
