### PR TITLE
Update settings.rs

### PR DESCRIPTION
**Pull request by WushuWorks**
test these two resizing and scaling settings and found them to not work on web releases. 
Update here for future users.

They don't do anything on the web releases

## Motivation and Context

This helps better inform users of available functionality

## Types of changes

- Breaking change (fix or feature that would cause existing functionality to change)
- New feature (non-breaking change which adds functionality)
- Bug fix (non-breaking change which fixes an issue)

Changed two comments

## Checks

- [x] I have read `CONTRIBUTING.md`.
- [x] This Pull Request targets the right branch 
- [x] I have updated `CHANGES.md`, with [BREAKING] next to all breaking changes
- [x] I have updated the documentation accordingly if necessary
- [x] I have updated / added tests to cover my changes if necessary

### CODE REVIEW

**Comment by WushuWorks** [comment]
It is. Setting those should be handled when you first start the core game loop, correct? I set them before the game boots with the Settings struct the [same way](https://github.com/WushuWorks/I-am-the-Elder-God/blob/master/src/main.rs) Quicksilver Rougelike does. 

If you look at my previous commits you can find that the desktop version will use the settings but the browser version will not. Would screenshots help?

**Comment by ryanisaacg** [comment]
I'm confused as to what isn't working for you with ImageScaleStrategy: it is meant to describe what happens when you draw an image at a size different than its raw pixels (for example, when blowing up a 16x16 image to 32x32, should it simply show up with each pixel 4 times as bigger or with some kind interpolation?)

Is that not working for you on web?

**Comment by ryanisaacg** [comment]
I'm going to close this, because it targets the old 0.3 API. Feel free to re-open if you want to keep working on, though.

**Comment by WushuWorks** [comment]
It's been a bit, but I remember things not actually scaling on the web. I.E. it would render at native resolution and would just cut when resized.

**Pull request closed without merging**
