### PR TITLE
Improve timer

### PR DESCRIPTION
**Pull request by lenscas**
A pull request for #590 . It also adds a way to reset the starting point of a timer, which may be useful when switching scenes and you don't want your game to try and catch up if there was lag.

## Motivation and Context
See #590 

## Checks
- [X] I have read `CONTRIBUTING.md`.
- [x] I have updated `CHANGES.md`, with [BREAKING] next to all breaking changes
- [x] I have updated the documentation if necessary

- [x] The example found in `README.md` compiles and functions like expected

### CODE REVIEW

**Comment by lenscas** [comment]
Ideally exhaust would just use some math rather than a loop to determine how many ticks have passed but I remember looking for something I could use and not finding it so I guess a loop will do for now?

**Comment by lenscas** [comment]
seems like the nightly compiler crashed during the integration test
```
   Compiling stdweb-derive v0.5.3
thread 'rustc' panicked at 'called `Option::unwrap()` on a `None` value', src/librustc/hir/mod.rs:81:37
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports
```
:(

**Comment by ryanisaacg** [comment]
Huh, I've been having trouble reproducing this but it definitely occurs on every run of CI. That's not great.

**Comment by ryanisaacg** [comment]
Well, after a good period of time with components not building on various nightlies, the stars have aligned and CI has passed!

**Pull request merged**
