### PR TITLE
[WIP] Tutorials

### PR DESCRIPTION
**Pull request by Xoronic**

### CODE REVIEW

**Comment by Xoronic** [comment]
5000 lines of code because I 'built' the book. In the future I won't build it :)

**Comment by Xoronic** [comment]
Or should I build it, as it is part of the static website.. What do you think?

**Comment by ryanisaacg** [comment]
I've definitely seen mdbooks in other projects, but I've never looked into how they host them. I'd prefer not to have the generated HTML checked into the repo, but if there's no convenient way to host it elsewhere then I'm open to committing it.

**Comment by Xoronic** [comment]
We could create another repository just for the book.. I think we should at least always create separate commits for the updated build and the updated source.

**Comment by Xoronic** [comment]
Nevermind, I don't think creating another repo is desirable, we would get issues with the different API versions and the docs with it.

**Comment by ryanisaacg** [comment]
If we were to go with another repo, it would make sense to move everything to its own organization, which seems like more overhead than it's worth. We can probably get by just updating the builds of the book when releases are made, because that way master, crates.io, and the book will all be in sync.

**Comment by Xoronic** [comment]
Since the fork got pretty messy because of the build, I will close this one and reopen it later.

**Pull request closed without merging**
