### PR TITLE
Add tarpaulin-based codecov support

### PR DESCRIPTION
**Pull request by ryanisaacg**
Code coverage would be nice to have, and now that tarpaulin can replace kcov it should be easier and more reliable.

### CODE REVIEW

**Comment by Byter09** [comment]
I have tarpaulin running for a pretty long time and I can only suggest this:
- cache the cargo directory
- install cargo-update

This way you do not always have to compile it. You remove like 10 minutes or so from the pipeline. I'll post the gitlab-ci.yml part that's responsible for that later when I'm home.

**Comment by Byter09** [comment]
Okay, so I know travis is a bit different, but maybe you can translate the following bits into travis-working-instructions:

This is for caching the cargo directory in every job, not only tarpaulin. 
```yml
cache:
  key: "$CI_JOB_NAME"
  paths:
    - .cargo/
```
My build template for all the different targets looks like this:
```yml
.build_template: &build
  image: "rust:latest"
  stage: build
  allow_failure: false
  only:
    - branches
    - development
    - web
  except:
    - master
  before_script:
    - apt-get update
    - apt-get -y install libasound2-dev libudev-dev $EXTRA_PACKAGES
    - mkdir -p target
    # overwrite cargo registry
    - (cp -ruT .cargo/ $CARGO_HOME/ && rm -R .cargo/) || true

    - rustup target add $TARGET || true
    - cargo update

    # debug version output
    - rustup -vV
    - cargo -vV
    - rustc -vV
```
and using that together with the actual coverage job it looks like this:
```yml
coverage:
  <<: *build
  variables:
      RUSTFLAGS: "--cfg procmacro2_semver_exempt"
      EXTRA_PACKAGES: "libssl-dev pkg-config cmake zlib1g-dev"
      TARGET: "x86_64-unknown-linux-gnu"
  coverage: '/\d+.\d+\% coverage/'
  allow_failure: true
  script:
  # Update tarpaulin if in cache
  - cargo install cargo-update || true
  - cargo install-update --all

  # Install tarpaulin itself if necessary
  - cargo install cargo-tarpaulin || true

  - cargo tarpaulin --verbose
```

Notice, that there is no such default cargo directory ".cargo" but because we can not cache anything outside of the repository directory, I'm moving and copying files to help me out a bit.
```yml
after_script:
  # cache cargo
  - mkdir .cargo
  - mv -T $CARGO_HOME/ .cargo/ || true
```


I'm also using `|| true` to prevent the pipeline from aborting too soon, even if errors occur. This helps if the cache is for some reason not available and .cargo does not exist. But this is also rebuilt-compatible, meaning if no cache ever was present, it will build one for you for the next pipeline call. This reduces my coverage report times from about 30 to 5 minutes.

**Comment by ryanisaacg** [comment]
Thanks! Not having to re-compile tarpaulin every build will definitely be nice. Currently I'm still just beating my head against getting the post-success script to run at all, but once I have that I'll try to travis-ify your config.

**Comment by Byter09** [comment]
> travis-ify

Hah!

Also, if I remember correctly, you also have to add codecov as an integration to your GitHub project, so that merge requests and their checks (as below) show the coverage and whether it went up or not.

Oh and one more thing: I'd suggest not using tarpaulin in the after_success, but only the coverage upload. But I have no idea how travis works and I can only suggest using gitlab's CI all the time (you know, the seperate thing where its only used as a CI and not as a repo (though I'm not sure 2000min are enough for you)). Well except for Windows. You'd need your own runner for that :P (but you can use mingw! :D)

Good luck I guess!

**Pull request merged**
