### PR TITLE
Add wasm to travis-ci.

### PR DESCRIPTION
**Pull request by memoryruins**
#238

### CODE REVIEW

**Comment by memoryruins** [comment]
The 0.5.1 rand error is left in the above so that you see what I ran into.

**Comment by ryanisaacg** [comment]
That's really cool! Once the upstream rand rand issue is fixed, this will be great to have.

**Comment by ryanisaacg** [comment]
Stdweb integration is merged! Feel free to merge in the development branch to get the update, which should make this PR mergeable.

**Comment by memoryruins** [comment]
Fantastic, well done with the integration! Merged while on the go and made a mess; however, It passes on travis :)

**Pull request merged**
