### PR TITLE
Fix typed events and some key bindings on web

### LINKED ISSUE #469: Event::Key(Key::Colon, ..) does nothing on web

### PR DESCRIPTION
**Pull request by ryanisaacg**
## Motivation and Context

Resolves #469 

## Types of changes

- Bug fix (non-breaking change which fixes an issue)

## Checks

- [x] I have read `CONTRIBUTING.md`.
- [x] This Pull Request targets the right branch 
- [x] I have updated `CHANGES.md`, with [BREAKING] next to all breaking changes
- [x] I have updated the documentation accordingly if necessary
- [x] I have updated / added tests to cover my changes if necessary
- [x] Pressing "backspace" yields typed events for 'B', 'a', 'c', ... 'e'

### CODE REVIEW

**Comment by rickyhan** [comment]
Typed event only triggers on alphanumeric text input.

**Comment by ryanisaacg** [comment]
True, I'm unsure of a good heuristic as to what is a printable character for Typed and what isn't (the keycode for 'Left Arrow' probably shouldn't get sent to Typed, but '-', '_', etc. should)

**Comment by ryanisaacg** [comment]
I was taking a look at some of the key bindings and I realized that there is already a key that captures 'Minus' from the keyboard: `Key::Minus`. `Key::Subtract` should map to `'NumpadSubtract'` instead.

Additionally, the printable non-alphanumeric ASCII characters should be included in `Typed` events, so that should solve your particular problem with wanting to get typed '-' characters. I'll make that a separate PR.

**Comment by rickyhan** [comment]
Awesome thanks!

**Comment by ryanisaacg** [comment]
@rickyhan CI is passing on this, so I'm going to test this tonight when I get a chance then merge.

**Pull request merged**
