### PR TITLE
Add variable tick rate and queryable fps counters

### LINKED ISSUE #314: variable draw and update rate
Hi again.

So from what I read in some issues, the draw rate depends on v-sync, right? This is fine I guess.
But what about the update rate; why is it so low?
https://github.com/ryanisaacg/quicksilver/blob/d9d2ef00758d56bbe5922724dc9755f3a15356c8/src/state.rs#L133
This looks like the line giving the timer the tick rate. But why 16 ms? The end result from my calculations is, that `update` is called every 20 ms and `draw`  every 5 to 7 ms (on my 144hz monitor). (I used `Instant` and `.elapsed()` to get the time between calls.)

Now I know, that this is all pretty normal and should work for 90% of users, but I'm currently working on something, that requires a bit more than just 20ms. In fact, I would need `update` to be called as often as possible. (It's a physics problem which requires a really high physics-step, and I would _love_ to use quicksilver for this!)

---

I'm proposing a (hopefully) minor change, in that `update` and maybe even `draw` are called as often as possible. Additionally both should have an additional parameter giving the `Duration` that passed, since they were last called.

Positive effects of this are:
- the user can interpolate calculations more precise, as 20ms is just huge
- fps- and calculation-limiting methods can now be implemented by the user
- if quicksilver provides default limits, nothing changes on the API (except maybe 2 new methods to change the limits)

There are no negative effects that come to mind.

I hope this receives positive feedback and of course I'll help out wherever I can.

### PR DESCRIPTION
**Pull request by ryanisaacg**
## Description

Add new functions to Window to determine how much time an update consumes from the accumulator. In doing so it became necessary to refactor the `state` module into a more general `lifecycle` module.

## Motivation and Context
 
Resolves #314

## Types of changes

- Breaking change (fix or feature that would cause existing functionality to change)

## Checks

- [x] I have read `CONTRIBUTING.md`.
- [x] This Pull Request targets the right branch.

**Documentation**
- [x] I have updated `CHANGES.md`, with [BREAKING] next to all breaking changes
- [x] I have updated the documentation accordingly if necessary

**Testing**
- [x] I have updated / added tests to cover my changes if necessary

**If this Pull Request introduces a breaking change**
- [x] The example found in `README.md` compiles and functions like expected
- [x] The example found in `src/lib.rs` compiles and functions like expected

- [x] Aggregate less time for `average_fps`
- [x] Add an opt-out / configurable frame time cap to avoid death spiral

### CODE REVIEW

**Comment by Byter09** [comment]
I'm on my phone right now but I'm sure I saw that right: self.tick_count() is only getting bigger right? Wouldn't a fps counter over the last... Let's say 1 second be better? You don't want that value to reach it's maximum. (I know f64 is pretty big but.. Just for safety reasons?...)

Also, Duration was not fully available then from what I see?

Oh and this does only affect update() right?

**Comment by ryanisaacg** [comment]
Yeah, with a 64-bit float we're definitely not going to overflow (unless someone runs a Quicksilver application for a few million years) but accuracy loss might not be ideal. I'll think about trying to keep it to one second or one minute or something.

Instant was not available, and so I stuck with just `f64` as it maps better onto `Duration` for desktop and `Date` for web.

For vsync and `requestAnimationFrame` reasons draw will *report* what fps it's getting, but it won't allow you to change it. You can tell update what delta time to try to achieve for updates (and it will run multiple ticks as necessary to hit the target, see [this renowned blog post](https://gafferongames.com/post/fix_your_timestep/) for details on the strategy I'm using)

Currently, there is a pretty gnarly failure mode sometimes called a "death spiral:" if the time it takes to update is greater than the target tick rate, every frame another `update` will be called in an attempt to catch up. In a situation where some large particle burst has slowed down rendering temporarily, this means that the update *will* catch up eventually; if the user's computer is too slow to complete a frame in the allotted time, the update *won't* catch up, but eventually become unusable. A possible solution to this is to cap the amount of time the application will try to use to catch up on updates. If 3 ticks are needed to reach parity and there is only time for 2, the simulation will slow down rather than crashing; this is an acceptable failure mode for a non-networked app but not for a networked one.

Personally I think the best solution is opt-out frame time caps, so that by default apps will slow down rather than have the possibility of entering a "death spiral," but developers can opt-out if they wish.

**Comment by Byter09** [comment]
So... simply running as fast as possible and restricting it "afterwards" is not an option?

Imagine setting the tick to... 0. Whatever. Some value that says "let the CPU kick the bucket". Now, the user could theoretically implement a "pause" generator themself. Great for my physics stuff. A "normal" user however could set it to something sane or leave it on default and quicksilver's internals could take over the timing. I don't really see a point in "catching up" if quicksilver can provide the time since the last update call. This is way simpler and allows a wider range of.. "usefulness". But that's just my opinion. Also no death spiral-y thing.

If your idea allows what I mentioned above, I'm quite certain this is a good start. Now all I need is this in development and a benchmark in my prototype :D

**Comment by ryanisaacg** [comment]
Generally, physics engines do bad things when you give them largely varying delta times, and there isn't a great way to do as-fast-as-possible on web (you need to give a timeout, and the browser engines generally don't respect timeouts that are very low.)

Personally I'd recommend in your case just requesting a time step of something like 5 ms, which should get the most consistent behavior, but I suppose making the decision to fix timestep for users might cross a line from convention-over-configuration into making the framework too rigid.

I think I'll merge this as-is and work on a second PR that adds support for unlocked update and draw rates (as well as update delta times.) Does that sound good?

**Comment by Byter09** [comment]
Yes. Possibly as a feature or something only allowed on desktop? Not sure. I mean this is where it'll be most useful I guess.

But yeah thanks for considering it!

**Comment by Byter09** [comment]
Oh yes I'm also a bit dumb. I just noticed, that this only counts for `draw()` as it should. For some reason (probably because you're doing this at times, when its like 3 am here and I can only fly over the code on my phone) I thought this was for `update()` too and just imagined what would happen if you raised the tickrate.

But yes I guess at 60hz this should be fine for a pretty long time :D

**Comment by Byter09** [comment]
Holy crap! I just tested this out (had to update because we're using the development branch as a dependency) and because you allowed a max_ticks amount, I'm reaching 20.224µs between `update()`.
My god is this fast. Only problem: There's no default limit and I can not even draw a single line anymore, the screen stays black :D Maybe there should be some kind of default value... 😝

**Comment by ryanisaacg** [comment]
This is what happens when I refactor while tired. Anyway, a bad merge caused me to lose some changes from the no-present-call PR, which meant that vertices weren't being flushed. I've got a PR to fix it in now: #339

**Pull request merged**
